name: brightway_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas=2.2.3
  - numpy=1.26.4
  - matplotlib=3.10.1
  - ipykernel=6.29.5
  - pip
  - pip:
      - bw2data==4.4.2
      - bw2io==0.9.6
      - bw2calc==2.0.1
      - premise[bw25]
      - python-dotenv==1.0.1
